version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka-1:
    build: .
    ports:
      #- "9092:9092"
      - "9093:9092"
    environment:
      #PORT_COMMAND: 'docker port $$(hostname) 9092/tcp | cut -d: -f2'
      KAFKA_ADVERTISED_HOST_NAME: 10.253.163.97
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.253.163.97:9093
      KAFKA_CREATE_TOPICS: "TopicA:3:3,TopicB:1:3"
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.253.163.97:_{PORT_COMMAND}
      #LISTENERS: PLAINTEXT://10.253.163.97:9092
      #KAFKA_CREATE_TOPICS: "lambda1:1:1"
    #volumes:
    #  - /Users/ualter/Developer/docas/kafka/volume/docker.sock:/var/run/docker.sock
  kafka-2:
    build: .
    ports:
      #- "9092:9092"
      - "9094:9092"
    environment:
      #PORT_COMMAND: 'docker port $$(hostname) 9092/tcp | cut -d: -f2'
      KAFKA_ADVERTISED_HOST_NAME: 10.253.163.97
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.253.163.97:9094
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.253.163.97:_{PORT_COMMAND}
      #LISTENERS: PLAINTEXT://10.253.163.97:9092
      #KAFKA_CREATE_TOPICS: "lambda1:1:1"
    #volumes:
    #  - /Users/ualter/Developer/docas/kafka/volume/docker.sock:/var/run/docker.sock  