version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.253.163.97
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.253.163.97:9092
      KAFKA_CREATE_TOPICS: "TopicA:3:1,TopicB:1:1"
    volumes:
      - /Users/ualter/Developer/docas/kafka/volume/docker.sock:/var/run/docker.sock
