version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka-1:
    build: .
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.253.163.97
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.253.163.97:9093
      #KAFKA_CREATE_TOPICS: "TopicB:1:1"
    volumes:
      - /Users/ualter/Developer/docas/kafka/volume/docker.sock:/var/run/docker.sock
  kafka-2:
    build: .
    ports:
      - "9094:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.253.163.97
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.253.163.97:9094
      #KAFKA_CREATE_TOPICS: "TopicB:1:1"
    volumes:
      - /Users/ualter/Developer/docas/kafka/volume/docker.sock:/var/run/docker.sock
  kafka-3:
    build: .
    ports:
      - "9095:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.253.163.97
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.253.163.97:9095
      KAFKA_CREATE_TOPICS: "TopicA:3:3,TopicB:1:1"
    volumes:
      - /Users/ualter/Developer/docas/kafka/volume/docker.sock:/var/run/docker.sock      